### ISSUE TITLE
Improve WP CLI Extendability

### ISSUE THREAD

**Issue by crstauf** [woocommerce/action-scheduler#265]
While we currently have just one command (`run`) for WP CLI, there's potential for many more:

- [ ] `add` (#255)
- [ ] `delete`/`clear`
- [ ] `pause` and `resume`
- [ ] `stats`/`info`
- [ ] `setting`
- [ ] `version` (#271)

I'm not saying all of the above commands have benefit (they're just examples). My point rather is the current state of WP CLI files and abstraction.

When ~creating `add` (#255)~ adding timestamps (#175), there were a couple of situations that would have been more easily solved if there was a base WP CLI class to handle processing of flags and output.

I'm thinking of a class structure like so:
- `ActionScheduler_WPCLI` - main commands handler
- `ActionScheduler_WPCLI_Command` - abstract class for commands
- `ActionScheduler_WPCLI_Command_Add` - class to handle `add` command

Given the technical nature of Action Scheduler, it's reasonable to expect even more WP CLI commands than those listed above, and so implementing a properly abstracted system sooner rather than later will allow for that development to occur more easily (I'm already anxious to work on some sort of `stats` command).

Interested in feedback and proposals, as well as whether this is something that's wanted, or has already been discussed (and deemed unnecessary).

Note: I think the custom tables feature plugin has a WP CLI command for migration, though I'm not sure what the impact of this issue would be there.

**Comment by crstauf** [comment]
Just put together a quick prototype of the abstraction structure (within one file), with an example of an improved integration of #175.

```php
WP_CLI::add_command( 'test', 'WPCLI_Test' );

class WPCLI_Test extends WP_CLI_Command {

	function foo( $args, $assoc_args ) {
		$helper = new WPCLI_Test_Foo( $args, $assoc_args );
	}

	function bar( $args, $assoc_args ) {
		$helper = new WPCLI_Test_Bar( $args, $assoc_args );
	}

}

abstract class WPCLI_Test_Command {

	private $time;

	function __construct( $args, $assoc_args ) {
		$this->time = WP_CLI\Utils\get_flag_value( $assoc_args, 'time', false );
		$this->init( $args, $assoc_args );
	}

	abstract function init( $args, $assoc_args );

	function log( $message ) {
		WP_CLI::log( $this->time . ': ' . $message );
	}

}

class WPCLI_Test_Foo extends WPCLI_Test_Command {

	function init( $args, $assoc_args ) {
		$this->log( __METHOD__ );
	}

}

class WPCLI_Test_Bar extends WPCLI_Test_Command {

	function init( $args, $assoc_args ) {
		$this->log( __METHOD__ );
	}

}
```

And output to Terminal:
<img width="1002" alt="Screen Shot 2019-03-23 at 9 38 29 PM" src="https://user-images.githubusercontent.com/4573033/54873760-0aabe400-4db4-11e9-9fec-cec98273aec7.png">

**Comment by crstauf** [comment]
@thenbrent Submitted PR, including #254.

**Comment by rrennick** [comment]
A quick note that `WP_CLI::add_command( 'test', 'WPCLI_Test' );` registers `wp test` vs `wp action-scheduler test`. `run` and `migrate` are subcommands.

I've been writing WP CLI commands for ~ 8 years and `migrate` is my first instance of using a separate class for a subcommand. [WooCommerce](https://github.com/woocommerce/woocommerce/tree/master/includes/cli) uses a separate class for the `update` subcommand. [WP CLI](https://github.com/wp-cli/wp-cli/tree/master/php/commands/src) uses 4 classes to handle all of the base commands.

While there are cases where functionality warrants implementing a separate class for a subcommand, creating a class for every subcommand isn't necessary for extensibility. Both `action-scheduler migrate` and `wc update` are good examples of implementing a separate class because the function served is separate from the remainder of CLI functionality offered.

Having said that, the list of features proposed in the description are worth investigating. One question I did have on the list was clarification on the pause/resume.

**Comment by crstauf** [comment]
Pause/resume would pause or resume the processing of scheduled actions. I can see this being of value when performing a bulk operation of some sort and you don't want actions being processed.

**Comment by rrennick** [comment]
> Pause/resume would pause or resume the processing of scheduled actions.

Agreed. We'd need to think about how to implement when there is a current terminal process is busy running actions.

**Comment by crstauf** [comment]
Closing in favor of https://github.com/crstauf/action-scheduler-cli.
