### ISSUE TITLE
Uninstall function?

### ISSUE THREAD

**Issue by SeanDS** [woocommerce/action-scheduler#395]
Is there an uninstaller for this library when bundled in another plugin? I searched for the relevant hooks but couldn't find anything. It's good practice to clean up after yourself, especially with v3 now adding database tables.

**Comment by thenbrent** [comment]
Hi @SeanDS - that’s a good point. I’m hesitant to delete the tables, because those tables are shared potentially with their plugins and losing data from them could be very bad. But I do agree, if we can know for sure a site is disabling the only plugin to use Action Scheduler, we don’t want to leave those tables behind.

**Comment by unfulvio** [comment]
Library could be bundled with multiple plugins though and may be necessary for these plugins to function properly. Currently Memberships, for example, bundles a copy to run since it supports versions of WooCommerce before they started bundling it. 

So I think, like Brent, it should be responsibility of individual plugins to remove their data from the tables at the very least.

Maybe AS could provide some uninstall helpers/API for third parties to remove their own items on AS on their respective uninstall routines? (Probably this might be already doable within functions api, in which case maybe just offer recommendation on docs/readme.)

**Comment by SeanDS** [comment]
@unfulvio: it would at least be nice if there was a function provided by Action Scheduler that could be called by a plugin's uninstaller, that would remove all traces of whatever this library adds. It would still be the responsibility of the plugin to run its uninstaller, but part of the uninstaller could be to call such a function.

**Comment by rrennick** [comment]
> it would at least be nice if there was a function provided by Action Scheduler that could be called by a plugin's uninstaller, that would remove all traces of whatever this library adds.

The way we handled this in WC Admin was use a private hook group (https://github.com/woocommerce/woocommerce-admin/issues/1528) and remove all AS data in that hook group when the plugin is deleted.

**Comment by unfulvio** [comment]
> it would at least be nice if there was a function provided by Action Scheduler that could be called by a plugin's uninstaller, that would remove all traces of whatever this library adds. It would still be the responsibility of the plugin to run its uninstaller, but part of the uninstaller could be to call such a function.

Then perhaps any uninstall-related functionality should address the issue whether more plugins are relying on the library; such is the case when you run WooCommerce - Memberships - Subscriptions; there might be multiple plugins accessing the library, or perhaps haven't accessed it yet and expect to find tables present. You run the risk otherwise having a single plugin removing too much and causing errors in others.

**Comment by thenbrent** [comment]
> You run the risk otherwise having a single plugin removing too much and causing errors in others.

You also very likely end up with the uninstall not actually running even when it's implemented.

For example, on a site with Plugin A and Plugin B both using AS, but only Plugin A supports the uninstall routine, if Plugin A is uninstalled then Plugin B, it will never run.

**Comment by SeanDS** [comment]
I guess this would be less of a problem if Action Scheduler prefixed all of its database entries (possibly even table names) with some plugin-specific key. I don't know if that is feasible.

**Comment by rrennick** [comment]
>I guess this would be less of a problem if Action Scheduler prefixed all of its database entries (possibly even table names) with some plugin-specific key.

That's what the `group` field that I mentioned in my previous comment is for. It up to the plugin/theme that implements AS to use the group field to identify its data.

There is not any practical way in PHP for a called library function to determine what set of functionality called it. Programming languages in general are not designed to do that.
