### ISSUE TITLE
Investigate Composer PSR-4 autoloading

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#434]
Per https://github.com/woocommerce/woocommerce/pull/25404#pullrequestreview-345255964 we'll need to look at switching to using the composer autoloading to allow AS to be added to WooCommerce (and other plugins) as an external.

**Comment by slaFFik** [comment]
@thenbrent @rrennick 
I would like to reopen the issue, because it does NOT fix the composer autoloading and actually does not load AS correctly.

In your `composer.json` you should have this:
```
"autoload": {
    "files": ["action-scheduler.php"]
},
```
As you determine the required lib version in that particular file, it should do all the loading by itself. The `classmap` key does nothing useful in terms of autoloading, it just lists where to find classes. But developers uses functions, not classes (as per your Usage doc).
In my test locally using `"files"` and removing `"classmap"` allowed to autoload AS.
