### ISSUE TITLE
Implementation queries / doc ommissions

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/action-scheduler#479]
Now that action scheduler has moved to custom tables, it's appropriate for a need I have in a public plugin. I'm currently porting my current implementation (based on https://github.com/deliciousbrains/wp-background-processing) to Action Scheduler, but I have a few implementation questions that I can't find answers to in the docs. 

If someone can quickly answer these, happy to pull a docs PR together. 

1. The docs mention that action scheduler initialises itself on init/1, but it doesn't indicate at what point in the WordPress hook lifecycle job events are fired. It would be helpful to understand what point all of my job handlers need to be hooked. Currently I'm doing it on init/2 but it might be helpful if I could do them later as it would clean up a few things in my codebase.

2. [Somewhat related] Clarify what happens if a task is due to run, but there is nothing attached to the relevant hook - does the job fail? will it re-try?

Thanks

**Comment by rrennick** [comment]
> It would be helpful to understand what point all of my job handlers need to be hooked.

These can be added as early as possible. The earliest point where they will be fired is during the WP cron run.

> Clarify what happens if a task is due to run, but there is nothing attached to the relevant hook

WP `do_action()` does not return a value (eg. status) or log whether anything was hooked. AS is the same.

**Comment by leewillis77** [comment]
> These can be added as early as possible. The earliest point where they will be fired is during the WP cron run.

Thanks, so hooks need to be registered before init/10 if my understanding is correct.

> WP do_action() does not return a value (eg. status) or log whether anything was hooked. AS is the same.

So jobs are fired, and removed from the queue, whether they're "successful" or not. Good to know.

**Comment by thenbrent** [comment]
> Thanks, so hooks need to be registered before init/10 if my understanding is correct.

Yes. That's right. A good point to document!

> So jobs are fired, and removed from the queue, whether they're "successful" or not. Good to know.

Yeah. Jobs are just actions, so they are abstracted from any callbacks on them.

It sounds like you're saying "successful" in terms of the operations run by callbacks on the action, but it's better to think of the job/action itself as having a status, partly because they do, but also because you never know for sure what is run on it, and what "success" means in terms of those callbacks. For example, a callback could run successfully, but a job/action still "fail", because a fatal error in some unrelated code causes it to be marked as failed.
