### ISSUE TITLE
Add dashboard method to recreate tables

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#491]
There are enough reports of AS tables being missing (including being deleted by the site owner via the WP Optimize plugin https://wordpress.org/support/topic/can-not-update-my-database/#post-12534740) that we should add a method to recreate the tables via the dashboard.

WooCommerce Reference: https://github.com/woocommerce/woocommerce/issues/25895

**Comment by thenbrent** [comment]
> we should add a method to recreate the tables via the dashboard

IMO, the tables should be automatically restored immediately rather than requiring manual intervention. Requiring manual action, as done with #492, means tables may be missing for a any given period of time. Scheduled events will be lost during that time, including critical events, like scheduled payments.

The one case I can see where AS is active and a site owner wouldn't want the tables automatically created - when they have been deliberately replaced with a different store - should be handled by custom data stores anyway, rather than deleting the tables directly in the DB.

IF AS 3.x is running with default data stores, its tables should exist.

**Comment by rrennick** [comment]
> when they have been deliberately replaced with a different store

This would be quite edge case as the migration won't run to a destination custom store but I can add a filter that could be used to disable this.
