### ISSUE TITLE
action-scheduler Migration in Process stuck

### ISSUE THREAD

**Issue by wundertips** [woocommerce/action-scheduler#504]
Hi,
I am having some major issue after upgrading to the Woocomerce 4.0. Unfortunately, i noticed the problem way to late. Upon upgrading, i pressed the START button to migrate all the historical data of orders and customers.

Now, the issue it that it will not stop spinning and in the scheduled log, nothing shows besides "2968 tasks pending". But the main field of hooks showing is empty. So there is no way to stop this task from the backend.

Somebody on your blog suggested to install the action scheduler stand a lone, which i did, but it created a fatal error:

2020-03-25T12:58:57+00:00 CRITICAL Uncaught RuntimeException: Unable to claim actions. Database error. in /var/www/vhosts/tigerbalm-baumetigre.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:675
Stack trace:
#0 /var/www/vhosts/tigerbalm-baumetigre.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(599): ActionScheduler_DBStore->claim_actions(2561893, 25, NULL, Array, '')
#1 /var/www/vhosts/tigerbalm-baumetigre.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(206): ActionScheduler_DBStore->stake_claim(25, NULL, Array, '')
#2 /var/www/vhosts/tigerbalm-baumetigre.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(154): ActionScheduler_HybridStore->stake_claim(25)
#3 /var/www/vhosts/tigerbalm-baumetigre.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler/classes/Act in /var/www/vhosts/tigerbalm-baumetigre.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 675 

It would be great to let me know how to get this solved. My programmer currently has completely disabled the action scheduler, but this can also not be the solution to the problem.

Some input is highly appreciated,

Sunantha

**Comment by rrennick** [comment]
@wundertips Github isn't for support. However, based on the info you provided your site may have the #437 issue.

> But the main field of hooks showing is empty. So there is no way to stop this task from the backend.

If you have actions that have an empty hook you can delete them using the checkbox at the left and delete bulk action.

> Somebody on your blog suggested to install the action scheduler stand a lone

The version of Action Scheduler in WooCommerce 4.0.1 is the latest version. You can tell from the stack trace `/wp-content/plugins/woocommerce/packages/action-scheduler/` that the functioning version is still the one in WC. You can remove the standalone version you installed.

> It would be great to let me know how to get this solved.

You can postpone the migration to custom tables by adding the following filter via a plugin `add_filter( 'action_scheduler_migration_dependencies_met', '__return_false' );`. That should eliminate the errors until the fix for #437 is released.

**Comment by wundertips** [comment]
thanks so much for your kind help. will forward the suggestion to my developer and update

**Comment by rrennick** [comment]
Closing this for lack of feedback. @wundertips If you have any followup please let us know.
