### ISSUE TITLE
Some cases of action getting timed-out

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [woocommerce/action-scheduler#514]
- WooCommerce `v3.9.0`
- WooCommerce Subscriptions `v3.0.1`
- Follow-Up Emails `v4.8.23`
- Mailchimp for WooCommerce `v2.3.1`

<hr>

We are having some cases where actions are failing with the message: `action timed out after 300 seconds`. When I queried the DB to find out the total count of such cases, I found:

Month      | Cases of timeout
----------|------------------
Mar 2020 | 4
Feb 2020 | 0
Jan 2020 | 126

#### Here are the actions that timed-out last month:

hook										| status	| scheduled_date_gmt	| scheduled_date_local	| args							| last_attempt_gmt		| last_attempt_local	|	claim_id
--------------------------------------------|-----------|-----------------------|-----------------------|-------------------------------|-----------------------|-----------------------|------------
sfn_followup_emails							| failed	| 2020-03-27 20:05:14	| 2020-03-27 15:05:14	|	{email_order_id:67946}  | 2020-03-27 20:05:14	| 2020-03-27 15:05:14	| 18738736
woocommerce_scheduled_subscription_payment	| failed	| 2020-03-27 19:54:17	| 2020-03-27 14:54:17	| {subscription_id:924119}	| 2020-03-27 19:55:06	| 2020-03-27 14:55:06	| 18737594
MailChimp_WooCommerce_Single_Order			| failed	| 2020-03-22 12:25:07	| 2020-03-22 07:25:07	| {obj_id:930365}			| 2020-03-22 12:26:02	| 2020-03-22 07:26:02	| 16746927
woocommerce_scheduled_subscription_payment	| failed	| 2020-03-09 21:35:51	| 2020-03-09 16:35:51	| {subscription_id:815780}	| 2020-03-09 21:35:55	| 2020-03-09 16:35:55	| 14266652

**Comment by rrennick** [comment]
@abhishek-pokhriyal Action Scheduler doesn't have any insight into why actions may have timed out. If debug logging was enabled the actions might have logged information to the debug log.

**Comment by abhishek-pokhriyal** [comment]
@rrennick Okay, is there any other place where apart from the `actionscheduler_logs` table to get more information? The logged message does not help much.
![image](https://user-images.githubusercontent.com/11808845/78559027-48e63b00-7831-11ea-9d47-38b7186661e9.png)

**Comment by rrennick** [comment]
> is there any other place where apart from the actionscheduler_logs table to get more information? 

WooCommerce extensions usually log to WooCommerce -> Status -> Logs.

**Comment by thenbrent** [comment]
> The logged message does not help much.

That's because in these situations, Action Scheduler has no idea what happened, and couldn't determine it while processing the action (otherwise, it would log more).

The `timed out after 300 seconds` log indicates that Action Scheduler found an action that had been in the `in-progress` statue for 5 minutes. Knowing that actions don't take 5 minutes to process (and even if they did, a server would almost never allow it that long to process), Action Scheduler treats it as failed and logs the generic error.

The most likely cause is server configuration killing the PHP process while the queue is being processed. If your server has a short timeline, like 20 seconds, you should increase that. 60 seconds is a good default. Action Scheduler will attempt to only process actions for 20 seconds in each request, but if you have a lot of other tasks running on WP Cron, or actions that take a long time to process (like 10-20 seconds), then a low server timeout may kill PHP before the action has a chance to finish processing.
