### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to ActionScheduler_Abstract_Schedule::__construct() must be an instance of DateTime, null given

### ISSUE THREAD

**Issue by DevKishan** [woocommerce/action-scheduler#555]
While visiting Action Schedulers' page, following error gets triggered
-- Fatal error: Uncaught TypeError: Argument 1 passed to ActionScheduler_Abstract_Schedule::__construct() must be an instance of DateTime, null given , Called in 
 /wp-content/plugins/sample-plugin-using-action-schedulers/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php on line 26 
 and defined in 
 /wp-content/plugins/sample-plugin-using-action-schedulers/libraries/action-scheduler/classes/abstracts/ActionScheduler_Abstract_Schedule.php:25 
 
 Stack trace: 
 #0 /wp-content/plugins/sample-plugin-using-action-schedulers/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(26): ActionScheduler_Abstract_Schedule->__construct(NULL) 
 #1 /wp-content/plugins/sample-plugin-using-action-schedulers/libraries/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(202): ActionScheduler_ActionFactory->get_stored_action('canceled', 'wpforms_admin_n...', Array, Object(ActionScheduler_NullSchedule), 'wpform in **/wp-content/plugins/sample-plugin-using-action-schedulers/libraries/action-scheduler/classes/abstracts/ActionScheduler_Abstract_Schedule.php** on line 25

-- The action scheduler causing this error was from WP Forms plugin as the error message says.

**Comment by rrennick** [comment]
Do you still have WPForms installed and active?

**Comment by rrennick** [comment]
@DevKishan I'm closing this due to lack of feedback. If you do want to follow up on this, you can still comment on the issue.

**Comment by slaFFik** [comment]
To those coming to this thread from a GH/google search.

The issue is not in the WPForms plugin, but in different Action Scheduler library versions that bundled inside different plugins.

WPForms bundles AS 3.1.6 (and uses async tasks - thus registering them and displaying in a table), the plugin that was named as `sample-plugin-using-action-schedulers` above - AS 3.1.4.
All AS lib versions below 3.1.5 had this issue: #522 - that is fixed in #527 and released in AS 3.1.5.
The fix is simple: update the bundled AS lib to the latest one inside `sample-plugin-using-action-schedulers` which was suggested to those developers.
