### ISSUE TITLE
Php 7.4 compatibility issue

### ISSUE THREAD

**Issue by RadhaRamasamy84** [woocommerce/action-scheduler#656]
Hi,

I am using version 'dev-release-225-amends' of this plugin (prospress/action-scheduler) . Php 7.4 compatibility check reports an error
' INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4' in '/classes/ActionScheduler_Compatibility.php' line 95. Is it safe to upgrade to 7.4 with this error? or do you have any plans to update the plugin to be php 7.4 compatible?

Can you please help?

thanks,
Radha

**Comment by amberhinds** [comment]
Hi Radha, 

We're using Action Scheduler in one of our plugins and it works fine on 7.4. You can safely upgrade your PHP and not have any problems with Action Scheduler.

WooCommerce team, I've also identified this warning while running tests with PHP Code Sniffer and would appreciate an update on if there are any plans to remove the deprecation? 

Thanks.

**Comment by rrennick** [comment]
> I've also identified this warning while running tests with PHP Code Sniffer and would appreciate an update on if there are any plans to remove the deprecation?

@RadhaRamasamy84 @amberhinds You can download the latest version of Action Scheduler from [WordPress.org](https://wordpress.org/plugins/action-scheduler/) or the [release page](https://github.com/woocommerce/action-scheduler/releases/tag/3.1.6). We won't be doing any new releases of AS 2.X.

**Comment by amberhinds** [comment]
@rrennick Thanks for the quick response.  We have version 3.1.6  installed and this deprecation is still present.

**Comment by barryhughes** [comment]
Hi @amberhinds and @RadhaRamasamy84—thanks for flagging this!

Despite the linter warnings (ie, the warnings emitted by either the PHP 7.4 compatibility tester or by PHPCS) I don't think this will cause a problem in practice, even if the code in question executes.

That said, in WooCommerce itself we have effectively the same code, but a [PHPCS ignore rule has been applied](https://github.com/woocommerce/woocommerce/blob/5.0.0/includes/wc-core-functions.php#L1682-L1692). I imagine we can do the same here (in Action Scheduler) or indeed we could remove that test from both codebases—since I'd think `safe_mode` is no longer an active concern, given it was removed in PHP 5.4, and since WordPress itself doesn't support anything earlier than PHP 5.6.20.

We'll address this in due course, though probably not as a high priority. Let me know if you disagree with that assessment!
