### ISSUE TITLE
DB update going on 6 hours. over 5000 completed actions so far. 

### ISSUE THREAD

**Issue by shopishopzar** [woocommerce/action-scheduler#657]
'update_callback' => 'wc_update_500_fix_product_review_count' 
'update_callback' => 'wc_update_500_db_version'

These two have run over and over for 6 hours since woocommerce suggested db update.

How long does this carry on for?

**Comment by vedanshujain** [comment]
It depends on number of products you have (there should be 1 action per 10 products), its intentionally slow to not put too much load on the website.
This is a backfill update and is relatively safe, so website will function normally while this going on.

**Comment by barryhughes** [comment]
Hopefully you are all set here, @shopishopzar — but do let us know if you are still experiencing this. Otherwise, we'll go ahead and close this in a few days time. Remember too that there are often better avenues than GitHub for seeking support, especially if you are using Action Scheduler in the context of WooCommerce:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
