### ISSUE TITLE
Job stuck in progress

### ISSUE THREAD

**Issue by jaschaio** [woocommerce/action-scheduler#684]
Occasionally a job keeps stuck in progress. Which is unfortuante as I only run one job at max. So once the job is stuck, no further actions are being executed:

![image](https://user-images.githubusercontent.com/11058666/113555651-912e6980-95fb-11eb-9080-802727741ffb.png)

If I delete the `in progress` job everything starts working again as expected.

But even if I would increase the number of simultanious jobs to be allowed, at some point I might still run into the issue of having all available jobs stuck `in progress`.

Shouldn't there be a mechanism that automatically removes stuck jobs after a defined timeout?

**Comment by barryhughes** [comment]
Adding an option to specify a cut-off or max allowed execution time sounds like something we could explore, ie:

```php
as_schedule_single_action(
	timestamp:   time() + HOUR_IN_SECONDS,
	hook:        'do_work',
	args:        [ 'data' => '123' ],
	group:       'plugin_x',
	max_allowed: 30 * MINUTE_IN_SECONDS,
);
```

However, will flag for discussion as there's quite a few things to consider here. Issues with the approach I sketched out:

* How can we reliably know if task execution stalled out and died, or if in fact it is still in progress?
* Can we guarantee being able to end task execution in all supported environments (in those cases where the task actually is still being processed, vs cases where it died)?
* What is a suitable status if we kill an in-progress task—failed? Or do we need a new status?
* Should it automatically be queued up for a re-try, or is that best left as a human decision? Should this be a further option that can be set programmatically?

Alternatives:

* Something close to the status quo (ie, the site operator needs to monitor things and take corrective action as needed; but we could improve messaging to increase awareness of problems as they arise).
* Instead of (or in addition) to supporting something like a `$max_allowed` param, we could add a global setting of some kind _(move 'in progress' tasks to 'stalled' after x minutes)._
* Other?

**Comment by barryhughes** [comment]
Worth noting that our docs state:

> If an action runs for more than 5 minutes, Action Scheduler will assume the action has timed out and will mark it as failed. However, if all callbacks attached to the action were to successfully complete sometime after that 5 minute timeout, its status would later be updated to completed.

It would seem in these cases that isn't happening.

**Comment by barryhughes** [comment]
@jascahio—

Sorry for the delay here. Per my last note this should already be taken care of and, circling back to this, I find I cannot replicate.

When the queue runner starts (this is true both when executed over HTTP, and via CLI) it runs a cleanup process. By default, any tasks that are 'stuck' (that is, they have been `in-progress` for more than 5 minutes) are updated to a status of `failed`.

Are you continuing to see this? If so, how long have the jobs been `in-progress` for and have you modifed the cleanup timeframe (such as via the `action_scheduler_failure_period` filter hook)? Any other information you can provide that might help us to replicate would be appreciated.

**Comment by jaschaio** [comment]
Hey @barryhughes, thanks for getting back to me. I haven't seen this happening again – which is odd because as far as I remember I haven't updated `action-scheduler` since I opened this issue, e.G. it is still running on `v3.1.6`.

Did the cleanup process you described got added recently or was it already present in `3.1.6`?

**Comment by barryhughes** [comment]
@jaschaio: yep, queue cleaning isn't new—it can be traced back in the history [about 7 years](https://github.com/woocommerce/action-scheduler/commit/743121a9ce24a27efcbacf02ec73a56b1f68c785). In terms of recent changes, there haven't been any that I'm aware of in relation to this sub-system: what you see in 3.1.6 is identical to what we have in 3.2.1.

> I haven't seen this happening again

Well, that's a good sign. 

Is it possible that it wasn't *just* clean-up that wasn't working, but a temporary problem with queue running in general?

If the queue is not being processed at all (which could be the result of many different causes such as hiccups with WP cron, mistakes in the system crontab entry, if you have one, or plain old plugin conflicts) then that will also impact clean-up, which 'piggy-backs' on top of the queue running process.

At any rate, since it sounds like the problem has gone, and there isn't enough information to diagnose a bug, I'll go ahead and close this (of course, let me know if you disagree and remember you can anyway create a fresh issue if needed in the future).
