### ISSUE TITLE
wpforms_admin_notifications_update FAILED !!! Woocommerce problem !!! bug

### ISSUE THREAD

**Issue by ghdfamily** [woocommerce/action-scheduler#694]
Yesterday I was updating my wordpress website and once I tried to update woocommerce This Happened:
<img width="1472" alt="Screen Shot 2021-05-12 at 5 54 22 PM" src="https://user-images.githubusercontent.com/84146878/118159849-8c738700-b3eb-11eb-9604-b36d8e1c6706.png">

Then everything was to sloww and I got these errors in my cPanel:
<img width="400" alt="Screen Shot 2021-05-12 at 5 59 20 PM" src="https://user-images.githubusercontent.com/84146878/118159917-a1e8b100-b3eb-11eb-9754-603140ebb3ee.png">

Woocommerce is trying to fix and upgrade it itself in scheduled actions and it is failing and it is on loop so it is falinig all the time:
![Screen Shot 2021-05-13 at 1 05 37 PM](https://user-images.githubusercontent.com/84146878/118160171-f68c2c00-b3eb-11eb-81b4-2fd7e35c0037.png)

bug #bug

**Comment by barryhughes** [comment]
Hi @ghdfamily—sorry to hear that :-(

It looks like a few different things are afoot but I'll note that the scheduled action listed in the screenshot you shared does not appear to relate to the WooCommerce update specifically, or even to WooCommerce at all: the prefix (`wpforms_`) suggests a forms plugin.

Since I don't think there is a problem with Action Scheduler itself, I'll go ahead and close this issue. If you are still facing problems with updating WooCommerce, consider reaching out via the [support forums](https://wordpress.org/plugins/woocommerce/) and someone will hopefully be able to assist further (this issue tracker is however reserved for bug reports and feature requests relating specifically to Action Scheduler).

Thanks!
