### ISSUE TITLE
Problems adding action

### ISSUE THREAD

**Issue by oceanvantage** [woocommerce/action-scheduler#708]
Hi
I'm running a plugin called Scrapes. Since May 9th, despite no code changes, the plugin has been unable to queue an action.

Has there been any changes in Action Scheduler since may 9th? What can cause action schedule to prevent a plugin from adding a scheduled action?

Thanks in advance.

**Comment by barryhughes** [comment]
Hi!

You can effectively see our release history by [looking at this list of tags](https://github.com/woocommerce/action-scheduler/tags). In the future, we'll also update the changelog you can [find over here](https://wordpress.org/plugins/action-scheduler/#developers). 

I don't have any particular knowledge of 'Scrapes', but am I right in thinking it includes Action Scheduler? If so, it would be worth checking:

1. Which version of Action Scheduler it includes.
2. What else within the plugin, or the environment in which it is running, changed on or around the date you mentioned.

Right now I'm afraid there isn't enough information to really help with your question (and, the issue tracker isn't really intended as a support channel). You could also consider reaching out to the author of that other plugin, if you haven't already done so, so that they can debug on their end.

Thanks!

**Comment by barryhughes** [comment]
Since it's been a couple of weeks without an update (and there isn't enough information to do anything more, just yet) I'm going to go ahead and close this.
