### ISSUE TITLE
Function not executing

### ISSUE THREAD

**Issue by Niblu** [woocommerce/action-scheduler#716]
I have a plugin with a file called async.php that contains this:

```
add_action('insert_test_action', 'test_action');

as_enqueue_async_action('insert_test_action');

function test_action(){
  error_log("test function writes something to errorlog");
}
```

I run the file with URL or CLI and everything works fine, the "insert_test_action' is visible under scheduled actions tab, it says pending, then completed, either via cron, via admin panel or from clicking run. So I see the action and get status complete, but the code inside the test_action() doesn't get executed. I tried error_log, writing to file, deliberate errors etc... it just doesn't execute.

I also tried to do put as_enqueue_async_action('insert_test_action'); inside a function and then init that:

```

function test_init(){
  as_enqueue_async_action('insert_test_action');
}

add_action ('init', 'test_init');
```

But that doesn't even create a log of the action in scheduled actions.

I also tested it on my local enviroment, as well as a stanging enviroment on the actual server, so it's not the enviroment.

What am I doing wrong?

**Comment by barryhughes** [comment]
Hi @Niblu! Can you speak a little more as to where this code lives (for instance, is it your main plugin file)? It essentially looks fine but, for the callback to execute, you need to ensure it is loaded whenever Action Scheduler starts processing scheduled actions.

Most often, that is accomplished by including it within the main body of your plugin code (so that it is available on every request). Of course, you *probably* would not want your `as_enqueue_async_action()` call to execute on every request, or you will place a lot of duplicate scheduled actions in the queue :-)

**Comment by barryhughes** [comment]
Closing (inactive/not enough info).
