### ISSUE TITLE
How can i get trigger when completed a task?

### ISSUE THREAD

**Issue by kumarchandang** [woocommerce/action-scheduler#732]
I just want to update something in the database and show some notice after updated a task. any event for that get trigger my custom function after completed a task?

**Comment by barryhughes** [comment]
Hi @kumarchandang,

As this is a custom code related question (and because the issue tracker is focused chiefly on bug reports, etc) we'll close this issue in due course.

Some thoughts/notes first of all:

* You may be interested in the [`action_scheduler_after_execute`](https://github.com/woocommerce/action-scheduler/blob/3.2.1/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L66) hook.
* Perhaps you could simply further action from within your callback function?
