### ISSUE TITLE
Action Scheduler will not running if Page Load event not fired

### ISSUE THREAD

**Issue by kouroshfar** [woocommerce/action-scheduler#753]
I added a hook and also register my action, everything will work correctly if I was opened a wp dashboard or go to load a page. but if I want to close my all tabs in the browser, all my actions will be stopped and not worked.

accordion to the document and research on the web, I think everything should be ok. but not worked :|

**Comment by barryhughes** [comment]
Hi @kouroshfar,

There's some good information about how things work over on [actionscheduler.org](https://actionscheduler.org/):

> The scheduler will attempt to run every minute by attaching itself as a callback to the `'action_scheduler_run_schedule'` hook, which is scheduled using WordPress’s built-in [WP-Cron](http://codex.wordpress.org/Function_Reference/wp_cron) system. Once per minute, it will also check on the `'shutdown'` hook of WP Admin requests whether there are pending actions, and if there are, it will initiate a queue via an async loopback request.

This is important because it means that if there is zero traffic, nothing will be processed: the same basic problem applies to WP Cron and there are of course various ways to deal with this. For instance, most hosts will let you add a task to the system task scheduer ("cron"), which means tasks can be processed even when there is no 'real' traffic.

Some resources you may be interested in:

- [Hooking WP Cron into the System Task Scheduler](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/)
- [Action Scheduler: WP CLI Documentation](https://actionscheduler.org/wp-cli/)

**Comment by barryhughes** [comment]
Closing—feel free to post a fresh issue if you continue to hit this problem.
