### ISSUE TITLE
Limitation of `as_schedule_cron_action()`

### ISSUE THREAD

**Issue by shohag121** [woocommerce/action-scheduler#781]
Currently, cron scheduler can not be used for scheduling tasks on a certain day (Saturday or Sunday) of the first (second, third, fourth) week every month.

**Used schedule string example:**
```
0 12 ? 1/1 SUN#2 *
```
**Thrown Exception**
```
InvalidArgumentException: Weekday must be a value between 1 and 5. 0 given
```

**Comment by shohag121** [comment]
I think `$weekday` should be treated as `$day_of_week` here instead of only weekdays of the week.
https://github.com/woocommerce/action-scheduler/blob/7f4aaf0e011bb0b41b266afd479f6935a495231b/lib/cron-expression/CronExpression_DayOfWeekField.php#L54

**Comment by barryhughes** [comment]
We're going to close this for the time being. It hasn't surfaced as a problem for other users, that we know of, and, even if the underlying library supports expressions like `SUN#2`, it's not a generally supported convention.

That said, we'd happily look at another PR if you want to raise one (we had some questions about the earlier PR that went unanswered, which is why that didn't move forward).
