### ISSUE TITLE
Race conditions with internal and external object cache

### ISSUE THREAD

**Issue by xpd** [woocommerce/action-scheduler#790]
Since a CLI worker can keep running indefinitely when there are enough jobs there is a high chance of running into race conditions with for example WooCommerce. This happens because other processes invalidating or changing the cache will do it on the external one and won't ever be picked up by the internal one usually stored in **$wp_object_cache->cache**. In the case of WooCommerce this could with some gateways result in missing order items or wrong calculations under high load.

AS by default clears the object cache when an external object cache isn't in use after **do_batch**, but this is mainly done to save memory. As these types of bugs are pretty hard for users to figure out how is happening I would suggest that AS implements some way to solve it for most of the popular object cache dropins.

There isn't an standardized way of clearing just the internal object cache when external ones is in use, but for some of the dropins this filter should get the work done without affecting how anything works. A similar logic can be used directly in action scheduler.

```
add_filter( 'action_scheduler_queue_runner_flush_cache', function( $flush ) {
	global $wp_object_cache;

	if ( ! wp_using_ext_object_cache() || ! ( isset( $wp_object_cache->cache ) && is_array( $wp_object_cache->cache ) ) ) {
		return $flush;
	}

	$wp_object_cache->cache = []; // reset the internal cache, without flushing the persistent object cache

	return false;
} );
```

**Comment by xpd** [comment]
I see this is partially solved by free_memory that I missed when first working on this. However what is important for the race conditions it is the actual time the internal cache can live. As we have jobs that can take both 100ms and 2 minutes it makes more sense to actually check if we should clear this based on the time since the last clear. For freeing memory it also makes more sense to check the total size of the memory in use than the number of jobs ran.

**Comment by barryhughes** [comment]
Hi @xpd, thanks for flagging this.

> Since a CLI worker can keep running indefinitely when there are enough jobs there is a high chance of running into race conditions with for example WooCommerce.

Yes. Though this problem at its core is not unique to Action Scheduler (or even to using the WP CLI-based queue runner), I can see that in those cases the risk of pulling incorrect values from the session cache has the potential to increases quite a bit.

> However what is important for the race conditions it is the actual time the internal cache can live. As we have jobs that can take both 100ms and 2 minutes it makes more sense to actually check if we should clear this based on the time since the last clear.

That's an interesting thought, and the `action_scheduler_begin_execute` hook may provide a reasonable way to do this (or even to do something more rigorous, if required, such as flushing the cache before each individual action).

> There isn't an standardized way of clearing just the internal object cache when external ones is in use, but for some of the dropins this filter should get the work done without affecting how anything works. 

That approach looks like it would work in many cases...yet I'm a little wary because when drop-ins define their own `WP_Object_Cache` they don't actually implement an interface (at least not formally), so there is a _lot_ of latitude as to how they might do things: it would be entirely possible for instance for `$wp_object_cache->cache = []` to trigger a flush of the persistent (external) cache.

Flagging for further discussion.

**Comment by tillkruss** [comment]
Calling `wp_cache_flush()` would be preferable here, since it allows each object cache implementation to handle the flush without depending on the `$cache` property.

**Comment by barryhughes** [comment]
Yes, but the reason we don't do that is to avoid dropping the persistent (external) cache.

**Comment by tillkruss** [comment]
This was just raised again in https://github.com/WordPress/performance/issues/36

What about introducing a new cache helper?

```php
/**
 * Removes all cache items from the runtime memory,
 * without flushing the persistent cache storage.
 *
 * @see WP_Object_Cache::flush_runtime()
 * @global WP_Object_Cache $wp_object_cache Object cache global instance.
 *
 * @return bool True on success, false on failure.
 */
function wp_cache_flush_runtime() {
	global $wp_object_cache;

	return $wp_object_cache->flush_runtime();
}
```

This could easily be implemented by the 3-4 major cache plugins and we can push core support through the performance team.

Any thoughts?

**Comment by barryhughes** [comment]
Yes, that looks like a nice solution to me—and then libraries/plugins like Action Scheduler could check if that function exists and call it if available.

Sidenote: though I realize the code above is mostly just illustrative, we'd probably want a method_exists() check within that function, too.

**Comment by JanThiel** [comment]
There are two thoughts on my mind regarding this. The first one is a bit radical though.... (no clickbait, promised ;-) )

1. If the caching backend is fast enough is there a real benefit of having the additional runtime cache in WP_Object_Cache at all? It seems to cause more trouble than it might do good. I do understand the value when the data is cached from a DB. But with modern in-memory caches like Redis I would at least challenge the value of the runtime cache for persistent read operations until proven otherwise by a real measurement. In this case skipping the runtime cache for read operations might be something to at least consider. As it is something the Caching layer can implement with no WP API change required it is also quite an opaque change. Disclaimer: I have no idea whether this is crazy or actually a possibly smart idea ;-) Some benchmarks are required to prove or falsify this. I couldn't find any data on this.
2. If the above is not the case and the runtime cache has a relevant impact on performance then flushing the whole runtime cache has to be considered an _expensive_ action. Yet by far not as expenive as flushing the persistent cache. The only effective way of a _selective_ cache flush is when the data is accessed. And then to only flush those keys at specific calls. Those calls (should?) know whether there might be a possible race condition or not. That's why I propsed exposing the `$force` attribute of the `wp_cache_get/_multiple` methods to the data access layer above it (`get_post_meta` for example). But this is not mutual exclusive. A runtime flush is easy to implement and can do a lot of good. But if this is the case, then why not go back to 1 and skip the runtime cache completely?

My thoughts base on the fact that concurrency issues are nearly impossible to debug and cause a lot of headache. And modern in-memory caches could/should be fast enough to allow one to sacrifice some µs for less concurrency trouble.

Just let me know if this is just crazy :-) But I still feel that this is something to at least discuss and measure.

**Comment by barryhughes** [comment]
> In this case skipping the runtime cache for read operations might be something to at least consider ... Some benchmarks are required to prove or falsify this.

It's an interesting thought.

My instinctive reaction is that both reading and writing to what we're calling the runtime cache here (a global PHP array) will still be *significantly* faster than calling out to an external process (be that Redis or something else) over TCP ... but I also lack any hard numbers.

> That's why I propsed exposing the $force attribute of the wp_cache_get/_multiple methods to the data access layer above it (get_post_meta for example). But this is not mutual exclusive. 

I agree, the two ideas (invalidating the entire runtime cache on one hand, and supporting selective invalidation/skipping on the other) are definitely not mutually exclusive and probably each would suit different scenarios.

Since we're in the Action Scheduler issue tracker here, I'll suggest that for our purposes a means of invalidating the entire runtime cache is *probably* the best fit (just because callbacks don't necessarily know if they are executing within a 'fresh' web request, or a long-running Action Scheduler process) and is probably the tool we would optionally consider using here ... but I definitely also see the value of the more targeted solution you've proposed outside of that context.

**Comment by tillkruss** [comment]
>My instinctive reaction is that both reading and writing to what we're calling the runtime cache here (a global PHP array) will still be significantly faster than calling out to an external process (be that Redis or something else) over TCP ... but I also lack any hard numbers.

It is, even when using [Relay](https://relaycache.com) or APUc, reading a PHP array is faster.

>If the above is not the case and the runtime cache has a relevant impact on performance then flushing the whole runtime cache has to be considered an expensive action.

I tend to prioritize simplicity and backwards compatibility over ultra-fine-grained cache control, especially when it comes to messy WordPress.

**Comment by barryhughes** [comment]
Placing `on hold` pending the outcome of https://github.com/WordPress/performance/issues/81 (since ideally we will make an update here once a canonical solution exists in WP itself—though let me know if I've misunderstood anything on this count).

**Comment by tillkruss** [comment]
https://core.trac.wordpress.org/ticket/55080#ticket

**Comment by tillkruss** [comment]
Merged into core: https://core.trac.wordpress.org/changeset/52772
