### ISSUE TITLE
Race conditions affecting ActionScheduler_QueueRunner::maybe_dispatch_async_request()

### ISSUE THREAD

**Issue by brandonpayton** [woocommerce/action-scheduler#793]
There are two race conditions that affect ActionScheduler_QueueRunner:
1. https://github.com/woocommerce/action-scheduler/blob/d9362151fbdb47620ccbe322ae42bddc004a0f2c/classes/ActionScheduler_QueueRunner.php#L103-L105 is a race because of the time between checking whether there is already a lock and attempting to obtain the lock. It needs to be a single action, where the code attempts to obtain a lock and does not proceed unless it succeeds.
2. https://github.com/woocommerce/action-scheduler/blob/d9362151fbdb47620ccbe322ae42bddc004a0f2c/classes/ActionScheduler_OptionLock.php#L27 is a race because multiple threads of execution can get the same lock option value and try to update at the same time, and nothing will stop each from updating the option value. One way to address this is to write an UPDATE wp_options query with a WHERE that is only satisfied if the option still has the previous, expected value. If the update does not affect any rows, then you did not successfully obtain the lock.

These can be argued to be race conditions based on the code, but we've also seen the effects of this in practice. While troubleshooting a customer issue, I added logging for the `action_scheduler_lock_async-request-runner` option and found the following in the logs:
```
[17-Dec-2021 06:44:13 UTC] update_option_action_scheduler_lock_async-request-runner OLD ('1639723449') NEW (1639723513)
[17-Dec-2021 06:44:14 UTC] update_option_action_scheduler_lock_async-request-runner OLD ('1639723449') NEW (1639723514)
```

Above, both option updates have the same old value, and both are setting a new value. This means two different things believe they obtained the same lock at the same time.

This was found while troubleshooting frequent MySQL deadlock for action scheduler table updates on WordPress.com Atomic sites.

**Comment by barryhughes** [comment]
Thanks for flagging this.

It does look possible that this could even lead to `max_concurrent_batches` being exceeded.

**Comment by jpSimkins** [comment]
Same issue that is crashing my site. We are currently looking into removing WooCommerce due to this locking up MySQL and crashing the site daily. Numerous issues with action scheduler but this is one that makes the site completely broken. Almost a year and the issue still persists.

**Comment by barryhughes** [comment]
Sorry to hear that, @jpSimkins.

Do you have any more details as to what is causing the crash? I'd assume it is not the race condition described in the opening post by itself (at least, not directly), but rather something that happens following that.

Something you could consider here is disabling async based queue runners using a snippet like this one:

```php
add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );
```

So long as WordPress scheduled events (ie, WP Cron) is working, the queue should still be processed and—if you have access to WP CLI in your hosting environment—you could additionally consider augmenting default WP Cron-based processing with a crontab rule along these lines:

```
* * * * * wp action-scheduler run --path=/path/to/wp
```

By eliminating the async queue runners (and, specifically, eliminating the related option lock race condition), this would reduce the chances of two or more attempts to stake claims at the same time (and the crontab rule, if you can set that up, would help to ensure that the queue of actions are still processed at a decent tempo).

**Comment by jpSimkins** [comment]
I am testing with the hook:
> add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );

I will create a new ticket for this since my issue seems to be related but not exact. I will collect more information for this and post it when I have organized data for this. Thank you

**Comment by andrewklimek** [comment]
If I'm reading right, this fix #967 only affects the async calls from admin pages.
Are race conditions still possible from WP Cron running the every minute schedule?  
It looks like WP Cron still just sets a transient, but they re-check it from the spawn async request.  I'm not sure if that's quite as foolproof as this implementation.

**Comment by barryhughes** [comment]
> Are race conditions still possible from WP Cron running the every minute schedule?

Great question. It probably requires some further analysis to determine that (especially as the transient API has different 'backends') 🤔 ... this is however an 'outer layer' of defence, with the action claim process acting as an inner layer. 

Are you encountering problems that look like they are related to the `cron` context?

**Comment by andrewklimek** [comment]
> Are you encountering problems that look like they are related to the `cron` context?

No I'm not, but I've been looking into the inner workings a bit for something I'm coding.
It seemed to me this method wp-cron uses (setting the lock with set_transient, adding lock to the ajax call, then checking the lock still matches) would be a nice thing to implement here, because it could save the direct db queries (and also could replace the nonce, perhaps).

A second thing I noticed here, is the timeout of 0.01 seconds is not respected by `wp_remote_post` ([it rounds up](https://github.com/WordPress/WordPress/blob/539ee9221bcf198416d937d49ae6ea2a10bd8acf/wp-includes/Requests/src/Transport/Curl.php#L427)) so we are always waiting 1 second when working in the backend of the site.  I've tested a direct `curl_exec` call in place of this function and indeed I get the 10ms I expected.

**Comment by barryhughes** [comment]
> It seemed to me this method wp-cron uses (setting the lock with set_transient, adding lock to the ajax call, then checking the lock still matches) would be a nice thing to implement here, because it could save the direct db queries

It's not clear to me that this approach is more robust, in the sense that I'm not sure it defends against race conditions quite as effectively as the atomic option lock we implemented, which is the number one consideration here. 

Happy to be persuaded otherwise (definitely do create a fresh issue to discuss), but unless it is at least as effective at guarding against race conditions, it's probably not an approach we would switch to.

> A second thing I noticed here, is the timeout of 0.01 seconds is not respected by wp_remote_post ([it rounds up](https://github.com/WordPress/WordPress/blob/539ee9221bcf198416d937d49ae6ea2a10bd8acf/wp-includes/Requests/src/Transport/Curl.php#L427)) so we are always waiting 1 second when working in the backend of the site.

To clarify, you mean there is always a delay of 1s when we dispatch the async queue runner? I see what you mean about the rounding, but the request is also set as non-blocking, and should return (almost) immediately regardless of the value of timeout.

I'm so far unable to replicate this problem locally, but if you are consistently seeing it can you create a fresh issue? That's easier for us to triage, than commenting on an existing closed issue.

Thanks!
